name: Selenium Test

on: [push]

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Chrome WebDriver
      run: |
        wget -N https://chromedriver.storage.googleapis.com/97.0.4692.71/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Run Selenium Tests
      run: |
        ./gradlew test
