name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Chrome WebDriver
      run: |
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -qP /tmp https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip -o /tmp/chromedriver_linux64.zip -d /tmp
        chmod +x /tmp/chromedriver
        sudo mv /tmp/chromedriver /usr/local/bin/

    - name: Run Selenium Tests
      run: |
        cd path/to/your/project  # Change path to your project directory
        ./gradlew test
